name: Build images

on:
  pull_request:

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Go 
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Set up env
        run: make env

      - name: Build images
        run: make build-images
