name: Publish container images

on:
  push:
    branches:
      - "stackhpc/release-*"

env:
  REGISTRY: ghcr.io/stackhpc

jobs:
  release-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Prepare Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Set up env
        run: make env

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish images
        run: GOOS=linux ARCH='amd64' VERSION=v1.23.0.1-shpc make upload-images
