name: Build CPO images [StackHPC]

on:
  push:
    tags:
    - v1.*-stackhpc

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the version from ref
      id: get_version
      run: echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

    - name: build & publish images
      run: |
        REGISTRY=ghcr.io/stackhpc ARCHS='amd64 arm64' GOOS=linux VERSION=${{ steps.get_version.outputs.VERSION }} make upload-images
